salmonella-team/discord-bot-cal

- .gitignore
- index.js
- package.json
- src/cal.js
- src/cal.ts
- src/message.js
- src/message.ts
- src/status.js
- src/status.ts
- src/type.js
- src/type.ts
- tsconfig.json
> 作り途中のキャルをマージする

- src/cal.ts
- src/message.ts
- src/speak.ts
https://github.com/salmonella-team/discord-bot-cal/issues/21
> yabaiwayoの後にfeedbackが来るようにする

- src/cal.ts
- src/message.ts
- src/speak.ts
https://github.com/salmonella-team/discord-bot-cal/issues/22
> キャルの音量を直接指定できるようにする

- src/message.ts
https://github.com/salmonella-team/discord-bot-cal/issues/27 ガードを追加して対処しました。
> helpの際の例外処理を追加した

- src/cal.ts
- src/message.ts
- tslint.json
https://github.com/salmonella-team/discord-bot-cal/issues/30 `/cal.vol`でも動くように変更
キャルのメッセージはコマンドとして認識しないようにも変更
> キャルの音量調整をスマートにした

- src/cal.ts
- src/message.ts
https://github.com/salmonella-team/discord-bot-cal/issues/36 ヤバいわよ！
> ヤバいわよ！のロールが付与されている場合はDevModeの切り替えができるようにした

- src/cal.ts
- src/message.ts
- src/spreadsheet.ts
https://github.com/salmonella-team/discord-bot-cal/issues/39 `/cal.list`で管理できます。
> ホワイトリストをDiscordのコマンドから管理できるように変更

- src/cal.ts
- src/message.ts
https://github.com/salmonella-team/discord-bot-cal/issues/45 DevMode用のに表示を増やしました。
> 通常時とDevModeの時でhelpの表示量を変更した

- src/cal.ts
- src/message.ts
https://github.com/salmonella-team/discord-bot-cal/issues/47
効果音-001とテスト用以外では動かないようになりました
> 指定のチャンネル以外でキャルが動かないようにする

- README.MD
- src/cal.ts
- src/spreadsheet.ts
https://github.com/salmonella-team/discord-bot-cal/issues/49 既に登録されているコマンドの場合はキャルが叱ります
> 同じ値をホワイトリストに追加できないようにする

- src/index.ts
https://github.com/salmonella-team/discord-bot-cal/issues/51 各botのおはように通知を送るようにした
> キャルがおはようという

- src/cal.ts
- src/message.ts
https://github.com/salmonella-team/discord-bot-cal/issues/52
> almageを削除した

- .gitignore
- src/index.ts
https://github.com/salmonella-team/discord-bot-cal/issues/55 誰かが移動しても宿屋の場合は移動しなくなった
> キャルが宿屋に着いていかないようになった

- dist/env.js
- dist/index.js
- dist/message.js
- dist/speak.js
- dist/spreadsheet.js
- src/env.ts
- src/index.ts
- src/message.ts
- src/speak.ts
- src/spreadsheet.ts
https://github.com/salmonella-team/discord-bot-cal/issues/59 環境変数を読み込む際、必ずエラーハンドリングを通すようにした。
> envのエラーハンドリングを一箇所にまとめた

- dist/index.js
- dist/message.js
- dist/ready.js
- dist/voiceStateUpdate.js
- src/index.ts
- src/message.ts
- src/ready.ts
- src/voiceStateUpdate.ts
https://github.com/salmonella-team/discord-bot-cal/issues/61 index.tsとMessageの中身を分離した
> モジュール分割をした

- config/settings.yaml
- dist/client/message.js
- dist/client/voiceStateUpdate.js
- dist/message/cal.js
- src/client/message.ts
- src/client/voiceStateUpdate.ts
- src/message/cal.ts
https://github.com/salmonella-team/discord-bot-cal/issues/73
> リモートヤバイわよ！を実装した

- config/settings.yaml
- dist/convex-management.js
- dist/index.js
- src/convex-management.ts
- src/index.ts
- tsconfig.json
#82 https://github.com/beroba/convex-management
> Add convex-managementの機能を追加

- src/client/message.ts
> Fix ヤバい → ヤバイ

- dist/client/message.js
- dist/client/ready.js
- dist/message/cal.js
- src/client/ready.ts
- src/message/cal.ts
> Add yamlに変えたけどコードは変えてなかった

- dist/client/message.js
- src/client/message.ts
> /rmでメッセージを消せるようにした

- dist/client/message.js
- dist/client/voiceStateUpdate.js
- dist/index.js
- src/client/message.ts
- src/client/voiceStateUpdate.ts
- src/index.ts
> botしか居ない場合キャルが入退出しないようになった

- config/settings.yaml
- dist/client/message.js
- dist/client/voiceStateUpdate.js
- src/client/voiceStateUpdate.ts
> usamaruのURLだけ独立

- config/settings.yaml
- dist/client/voiceStateUpdate.js
- src/client/voiceStateUpdate.ts
> 画面共有の開始・終了ログを取る 

- dist/client/message.js
- src/client/message.ts
> bpm計算機を実装した

- package.json
> node.jsのバージョンを14に変更

- config/settings.yaml
- dist/client/message.js
- package-lock.json
- package.json
- src/client/message.ts
> 声帯機能の調整を行う

- config/settings.yaml
- dist/client/message.js
- dist/client/voiceStateUpdate.js
- dist/config/etc.js
- dist/message/aloud.js
- dist/message/cal.js
- src/client/message.ts
- src/client/voiceStateUpdate.ts
- src/config/etc.ts
- src/index.ts
- src/message/aloud.ts
- src/message/cal.ts
- tsconfig.json
> 喋らせる言語・音声を増やす

- src/client/voiceStateUpdate.ts
> ログに時間を表示する

- Dockerfile
- docker-compose.yaml
Herokuの無料枠がなくなったためDocker化をし適当なサーバーでも動くようDocker化
コンテナレジストリーの設定をしていないので適当な状態になっていますので
今後のタイミングでgithub actionsなどでビルドしghcrなどにあげられるといいかも
> Dockerファイルを追加、レジストリーは適当

- src/message/speak.ts
> なんか操作ミスってコミットメッセージがない
